Repository hashicorp/terraform-provider-helm, pull requests merged in 2018-12, with the labels that each got.

#166 Fix acceptance tests
  helm/resource_release_test.go
Labels: size/XS

#168 Workaround for Helm race condition in tests
  helm/resource_release_test.go
Labels: size/XS

#165 Update index.html.markdown
  website/docs/index.html.markdown
Labels: documentation, size/XS

#151 Run acceptance tests on travis
  .travis.yml
Labels: size/M

#170 Change wait time in testAccCheckHelmReleaseDestroy to 30 seconds
  helm/resource_release_test.go
Labels: size/XS

#172 Fix build after dependency updates
  .gitignore
  scripts/compile.sh
Labels: size/XS
