Repository hashicorp/terraform-provider-helm, pull requests merged in 2019-01, with the labels that each got.

#174 Fix typo
  website/docs/index.html.markdown
Labels: documentation, size/XS

#178 Fix the travis build badge and update version
  README.md
Labels: size/XS

#177 provider.go: minor grammar fix
  helm/provider.go
Labels: size/XS

#176 readme: add file config config_path info
  website/docs/index.html.markdown
Labels: documentation, size/XS

#179 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
Labels: size/XS

#153 add the ability to use sensitive values
  helm/resource_release.go
Labels: size/S

#161 Fix when Helm provider ignores FAILED release state
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/M

#182 Log values.yaml in case of errors and filtering sensitive values
  helm/resource_release.go
Labels: size/XS
