Repository hashicorp/terraform-provider-helm, pull requests merged in 2019-02, with the labels that each got.

#194 Update default tiller image to v2.11.0 and document defaults
  helm/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#192 Adding the wait flag to the docs
  website/docs/release.html.markdown
Labels: documentation, size/XS

#202 Remove -i from 'go test' to allow running unit tests locally with go 1.11.x and GO111MODULE=on
  GNUmakefile
Labels: size/XS

#209 Updated documentation
  website/docs/release.html.markdown
  website/docs/repository.html.markdown
Labels: documentation, size/S

#193 helm_release: Suppress diff of "keyring" and "devel" attributes
  helm/resource_release.go
Labels: size/XS

#206 Add entries to .gitignore to roughly match the Google provider
  .gitignore
Labels: size/XS

#207 Using localhost for TillerHost leads to 'context deadline exceeded'
  helm/provider.go
Labels: size/XS

#211 Updated CHANGELOG preparing v0.8.0 release
  CHANGELOG.md
Labels: size/XS

#215 fix: config_path example
  website/docs/index.html.markdown
Labels: documentation, size/XS

#210 Use configured helm home when reading default TLS settings
  helm/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#222 Fix Travis and Minikube
  .travis.yml
Labels: size/XS

#218 fix config_path documentation
  website/docs/index.html.markdown
Labels: documentation, size/XS
