Repository hashicorp/terraform-provider-helm, pull requests merged in 2019-10, with the labels that each got.

#350 Fix release shield
  README.md
Labels: size/XS

#307 Fix loading kubeconfig when disabled
  helm/provider.go
Labels: size/XS

#364 Remove the install instructions
  README.md
Labels: size/S

#365 update tiller image
  helm/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#367 Prepare for release v0.10.4
  CHANGELOG.md
Labels: size/XS
