Repository hashicorp/terraform-provider-helm, pull requests merged in 2019-06, with the labels that each got.

#289 Update Terraform to 0.12.1
  go.mod
  go.sum
Labels: size/S

#282 helm/resource_release: typo fixes
  helm/resource_release.go
Labels: size/XS

#273 Add acceptance test cases for concurrent repositories additions issue
  helm/provider_test.go
  helm/resource_release.go
  helm/resource_release_test.go
  helm/resource_repository_test.go
Labels: size/L

#272 Fix concurrency issues reading multiple repos
  helm/data_repository.go
  helm/provider_test.go
  helm/resource_release.go
  helm/resource_release_test.go
  helm/resource_repository_test.go
Labels: size/L

#185 Automatically initialize the configured helm home directory
  .travis.yml
  helm/data_repository_test.go
  helm/provider.go
  helm/provider_test.go
  helm/resource_release_test.go
  helm/resource_repository_test.go
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/M

#293 Preparing release v0.10.0
  CHANGELOG.md
Labels: size/XS

#294 Update to Helm 2.14.1
  go.mod
  go.sum
  helm/provider.go
  vendor/github.com/BurntSushi/toml/session.vim
  vendor/k8s.io/helm/pkg/kube/client.go
  vendor/k8s.io/helm/pkg/tiller/environment/environment.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/M

#295 Wait for tiller if it's not ready
  helm/provider.go
Labels: size/XS
