Repository hashicorp/terraform-provider-helm, pull requests merged in 2019-03, with the labels that each got.

#221 Make helm_repository a data resource
  helm/data_repository.go
  helm/data_repository_test.go
  helm/provider.go
  helm/resource_repository.go
  helm/resource_repository_test.go
  website/docs/release.html.markdown
  website/docs/repository.html.markdown
Labels: documentation, size/XL

#231 Added load_config_file option to the provider k8s part
  helm/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#232 Updated CHANGELOG preparing v0.9.0 release
  CHANGELOG.md
Labels: size/XS

#233 Replace 'O' with '0' in unreleased version number
  CHANGELOG.md
Labels: size/XS

#234 Fix mistake in documentation
  website/docs/repository.html.markdown
Labels: documentation, size/XS

#227 Escape commas in set_string
  helm/resource_release.go
  helm/resource_release_test.go
  website/docs/release.html.markdown
Labels: documentation, size/S

#238 Codify infrastructure for running acceptance tests
  helm/test-infra/README.md
  helm/test-infra/gke/README.md
  helm/test-infra/gke/kubeconfig-template.yaml
  helm/test-infra/gke/main.tf
  helm/test-infra/install-helm-via-docker.sh
Labels: size/L

#237 Enable modules in Travis & go mod tidy
  .travis.yml
  go.mod
  go.sum
Labels: dependencies, size/L

#186 Allow running acceptance test cases concurrently in isolation
  GNUmakefile
  helm/resource_release_test.go
  helm/resource_repository_test.go
  vendor/github.com/hashicorp/terraform/helper/acctest/acctest.go
  vendor/github.com/hashicorp/terraform/helper/acctest/random.go
  vendor/github.com/hashicorp/terraform/helper/acctest/remotetests.go
  vendor/golang.org/x/crypto/curve25519/const_amd64.h
  vendor/golang.org/x/crypto/curve25519/const_amd64.s
  vendor/golang.org/x/crypto/curve25519/cswap_amd64.s
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/curve25519/doc.go
  vendor/golang.org/x/crypto/curve25519/freeze_amd64.s
  vendor/golang.org/x/crypto/curve25519/ladderstep_amd64.s
  vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go
  vendor/golang.org/x/crypto/curve25519/mul_amd64.s
  vendor/golang.org/x/crypto/curve25519/square_amd64.s
  vendor/golang.org/x/crypto/internal/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_s390x.s
  vendor/golang.org/x/crypto/internal/chacha20/xor.go
  vendor/golang.org/x/crypto/internal/subtle/aliasing.go
  vendor/golang.org/x/crypto/internal/subtle/aliasing_appengine.go
  vendor/golang.org/x/crypto/poly1305/poly1305.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_arm.go
  vendor/golang.org/x/crypto/poly1305/sum_arm.s
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ref.go
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/poly1305/sum_s390x.s
  vendor/golang.org/x/crypto/poly1305/sum_vmsl_s390x.s
  vendor/golang.org/x/crypto/ssh/buffer.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/connection.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/mac.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/mux.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/streamlocal.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#241 Update release.html.markdown
  website/docs/release.html.markdown
Labels: documentation, size/XS

#243 Fix small typo in file config documentation
  website/docs/index.html.markdown
Labels: documentation, size/XS
