Repository hashicorp/terraform-provider-helm, pull requests merged in 2019-08, with the labels that each got.

#310 Revert "Escape commas in set_string (#227)"
  helm/resource_release.go
  helm/resource_release_test.go
  website/docs/release.html.markdown
Labels: documentation, size/S

#314 Prepare for release 0.10.2
  CHANGELOG.md
Labels: size/XS

#253 Remove ForceNew on repo and chart changes
  helm/resource_release.go
Labels: size/XS

#324 Modernise docs
  website/docs/index.html.markdown
  website/docs/release.html.markdown
  website/docs/repository.html.markdown
Labels: documentation, size/M

#245 Don't enable TLS if `enable_tls` is false
  helm/provider.go
Labels: size/XS
