Repository hashicorp/terraform-provider-helm, pull requests merged in 2020-04, with the labels that each got.

#460 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
Labels: size/M

#464 helm_release: chart lint when `terraform plan`
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/M

#469 Add exec block documentation
  website/docs/index.html.markdown
Labels: documentation, size/XS

#466 helm_repository: deprecated
  helm/data_repository.go
  website/docs/d/repository.html.markdown
  website/docs/r/release.html.markdown
Labels: documentation, size/XS

#471 Add issue pruning tasks
  .github/workflows/prune_stale_issues.yml
  .hashibot.hcl
Labels: size/XS
