Repository hashicorp/terraform-provider-helm, pull requests merged in 2020-07, with the labels that each got.

#499 Update 'helm_release' resource docs for optional "type" parameter
  website/docs/r/release.html.markdown
Labels: documentation, size/XS

#538 typo
  website/docs/r/release.html.markdown
Labels: documentation, size/XS

#518 Added note on NOTES.txt to FAQ
  README.md
  _about/FAQ.md
Labels: size/XS

#545 Add Q3 2020 roadmap
  README.md
  _about/ROADMAP.md
Labels: size/S

#548 Update go-version for CVE-2020-14039
  .go-version
Labels: enhancement, size/XS, upstream
