Repository hashicorp/terraform-provider-helm, pull requests merged in 2020-08, with the labels that each got.

#565 Update docs for verify and chart attributes in helm_release
  .github/ISSUE_TEMPLATE/bug-report.md
  website/docs/r/release.html.markdown
Labels: documentation, size/XS

#482 Fix nil path for dependency_update flag
  helm/resource_release.go
  helm/resource_release_test.go
  helm/test-fixtures/charts/local-chart/Chart.yaml
  helm/test-fixtures/charts/local-chart/requirements.lock
  helm/test-fixtures/charts/local-chart/requirements.yaml
  helm/test-fixtures/charts/local-chart/templates/_helpers.tpl
  helm/test-fixtures/charts/local-chart/templates/deployment.yaml
  helm/test-fixtures/charts/local-chart/values.yaml
Labels: acknowledged, bug, size/M

#532 Added app_version to metadata attribute block
  helm/resource_release.go
  helm/resource_release_test.go
  website/docs/r/release.html.markdown
Labels: acknowledged, documentation, size/XS
