Repository hashicorp/terraform-provider-helm, pull requests merged in 2020-05, with the labels that each got.

#480 helm_release: cloak metadata.value and deprecate set_string
  helm/resource_release.go
  helm/resource_release_test.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/float.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/int.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/list.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/meta.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/network.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/strings.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/time.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/uuid.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/web.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#488 Move PR tests to GitHub Actions
  .github/workflows/tests.yaml
  .travis.yml
Labels: size/M

#487 Fix crash when chart fails linter
  helm/resource_release.go
  helm/resource_release_test.go
  helm/test-fixtures/charts/broken-chart/Chart.yaml
  helm/test-fixtures/charts/broken-chart/templates/service.yaml
Labels: size/S

#491 Add more meaningful deprecation warning to helm_repository
  helm/data_repository.go
Labels: size/XS
