Repository hashicorp/terraform-provider-helm, pull requests merged in 2020-12, with the labels that each got.

#632 Add v2 Upgrade Guide to docs
  website/docs/guides/v2-upgrade-guide.markdown
  website/helm.erb
Labels: documentation, size/M

#637 Set up matrix build to run acc tests against different tf versions
  .github/workflows/tests.yaml
Labels: size/XS

#644 Add v2.0.0 changes
  CHANGELOG.md
Labels: size/XS

#636 Add config_paths to kubernetes block in provider config
  helm/provider.go
  helm/structure_kubeconfig.go
  website/docs/index.html.markdown
  website/docs/r/release.html.markdown
Labels: documentation, size/L

#648 Move kubernetes config check out of providerConfigure
  helm/provider.go
Labels: size/XS

#650 hotfix new stable chart URL
  CHANGELOG.md
  helm/provider.go
Labels: size/XS
