Repository hashicorp/terraform-provider-helm, pull requests merged in 2020-03, with the labels that each got.

#421 Add timeout flag details
  website/docs/r/release.html.markdown
Labels: documentation, size/XS

#406 Fix install errors being swallowed when creating a helm_release
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/M

#394 Helm v3 import release feature
  helm/provider.go
  helm/resource_release.go
  helm/resource_release_test.go
  website/docs/r/release.html.markdown
Labels: documentation, size/L

#440 Upgrade helm to v3.1.2
  go.mod
  go.sum
  vendor/helm.sh/helm/v3/pkg/action/install.go
  vendor/helm.sh/helm/v3/pkg/action/pull.go
  vendor/helm.sh/helm/v3/pkg/action/upgrade.go
  vendor/helm.sh/helm/v3/pkg/chartutil/dependencies.go
  vendor/helm.sh/helm/v3/pkg/chartutil/save.go
  vendor/helm.sh/helm/v3/pkg/downloader/chart_downloader.go
  vendor/helm.sh/helm/v3/pkg/downloader/manager.go
  vendor/modules.txt
Labels: dependencies, size/M

#442 Example with chart not in repository
  helm/resource_release.go
  website/docs/r/release.html.markdown
Labels: documentation, size/XS

#407 Use kind to run acceptance tests in travis-ci
  .travis.yml
  helm/provider_test.go
  helm/resource_release_test.go
Labels: size/M

#447 Release v1.1.0
  CHANGELOG.md
  README.md
  helm/resource_release.go
Labels: size/S

#449 Fix repo/chart path bug causing unexpected diff
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/S

#453 Update CHANGELOG for 1.1.1
  CHANGELOG.md
Labels: size/XS

#455 Add github actions for issues+PRs
  .github/workflows/issues.yml
  .github/workflows/labeled_issues.yml
Labels: size/S
