Repository hashicorp/terraform-provider-helm, pull requests merged in 2020-06, with the labels that each got.

#514 Put helm lint behind an attribute
  helm/resource_release.go
  helm/resource_release_test.go
  website/docs/r/release.html.markdown
Labels: documentation, size/XS

#511 Improve readme
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  README.md
  _about/CONTRIBUTING.md
  _about/FAQ.md
  _about/ISSUES.md
  _about/PULL_REQUESTS.md
Labels: size/L

#522 Replace all instances of the old org with the new one
  README.md
  _about/CONTRIBUTING.md
  _about/ISSUES.md
  go.mod
  go.sum
  main.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/strings.go
Labels: dependencies, size/M

#505 Redirect klog to write to file instead of stderr to avoid blocking
  main.go
Labels: size/XS

#525 fix: avoid concurrent read/write in metadata (#494)
  helm/provider.go
  helm/resource_release.go
  helm/resource_release_test.go
  helm/structure_kubeconfig.go
  helm/test-fixtures/charts/basic-chart/Chart.yaml
  helm/test-fixtures/charts/basic-chart/templates/configmap.yaml
  helm/test-fixtures/charts/basic-chart/values.yaml
Labels: size/L
