Repository hashicorp/terraform-provider-helm, pull requests merged in 2021-04, with the labels that each got.

#702 Add support for storing the rendered manifest (i.e Helm diff support)
  go.mod
  go.sum
  helm/manifest_json.go
  helm/manifest_json_test.go
  helm/provider.go
  helm/provider_test.go
  helm/resource_release.go
  helm/resource_release_test.go
  helm/testdata/manifest_json/rendered_manifest.json
  helm/testdata/manifest_json/rendered_manifest.yaml
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/golang.org/x/crypto/sha3/doc.go
  vendor/golang.org/x/crypto/sha3/hashes.go
  vendor/golang.org/x/crypto/sha3/hashes_generic.go
  vendor/golang.org/x/crypto/sha3/keccakf.go
  vendor/golang.org/x/crypto/sha3/keccakf_amd64.go
  vendor/golang.org/x/crypto/sha3/keccakf_amd64.s
  vendor/golang.org/x/crypto/sha3/register.go
  vendor/golang.org/x/crypto/sha3/sha3.go
  vendor/golang.org/x/crypto/sha3/sha3_s390x.go
  vendor/golang.org/x/crypto/sha3/sha3_s390x.s
  vendor/golang.org/x/crypto/sha3/shake.go
  vendor/golang.org/x/crypto/sha3/shake_generic.go
  vendor/golang.org/x/crypto/sha3/xor.go
  vendor/golang.org/x/crypto/sha3/xor_generic.go
  vendor/golang.org/x/crypto/sha3/xor_unaligned.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/modules.txt
  website/docs/index.html.markdown
  website/docs/r/release.html.markdown
Labels: dependencies, size/XXL

#724 Manifest dry-run should be behind experiment toggle
  helm/resource_release.go
Labels: size/M

#728 Install Terraform version according to matrix in GH actions
  .github/workflows/tests.yaml
Labels: size/XS

#729 Remove GH workflow step to explicitly install Terraform
  .github/workflows/tests.yaml
Labels: size/XS

#580 Fix dependency download on resource update
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/L

#720 Add support for the --wait-for-jobs option
  _about/CONTRIBUTING.md
  helm/resource_release.go
  helm/resource_release_test.go
  website/docs/r/release.html.markdown
Labels: documentation, size/XS

#738 Update CHANGELOG.md - release 2.1.2
  CHANGELOG.md
Labels: size/XS

#727 Failed helm_release creation surfaces diagnostic to taint resource
  helm/resource_release.go
  helm/resource_release_test.go
  helm/testdata/charts/failed-deploy/Chart.yaml
  helm/testdata/charts/failed-deploy/templates/service.yaml
Labels: size/M

#483 New data source `helm_template` to render chart templates locally (v3)
  helm/data_template.go
  helm/data_template_test.go
  helm/provider.go
  website/docs/d/template.html.markdown
  website/docs/index.html.markdown
  website/docs/r/release.html.markdown
  website/helm.erb
Labels: documentation, enhancement, new-data-source, size/XL
