Repository hashicorp/terraform-provider-helm, pull requests merged in 2021-02, with the labels that each got.

#674 Read function should set resource id to null if not found
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/M

#673 Update provider configuration docs
  website/docs/index.html.markdown
Labels: documentation, size/S

#671 fix destroy stage error for charts with "helm.sh/resource-policy:keep" annotation
  helm/resource_release.go
Labels: size/XS

#684 Fix documentation for KUBE_TOKEN env var name
  website/docs/index.html.markdown
Labels: documentation, size/XS
