Repository hashicorp/terraform-provider-helm, pull requests merged in 2021-08, with the labels that each got.

#772 Fix issue with multiple manifests templating in helm_template data resouce.
  helm/data_template.go
Labels: size/XS

#759 [doc] update stable helm charts url
  website/docs/d/template.html.markdown
Labels: size/XS, documentation

#778 Add regression test for template bug
  helm/data_template.go
  helm/data_template_test.go
  helm/testdata/charts/test-chart/templates/configmaps.yaml
Labels: size/M
