Repository hashicorp/terraform-provider-helm, pull requests merged in 2021-01, with the labels that each got.

#657 FIX example in README.md
  README.md
Labels: size/XS

#660 Remove test output section from PR template
  .github/pull_request_template.md
Labels: size/XS

#659 Remove empty credentials check
  helm/provider.go
Labels: size/S

#667 Update v2-upgrade-guide.markdown
  website/docs/guides/v2-upgrade-guide.markdown
Labels: documentation, size/XS
