Repository hashicorp/terraform-provider-helm, pull requests merged in 2022-09, with the labels that each got.

#855 Do dependency update in resourceDiff #771
  helm/resource_release.go
  helm/resource_release_test.go
  helm/testdata/charts/umbrella-chart/templates/service.yaml
Labels: size/S

#960 fix flaky OCI test setup
  helm/resource_release_test.go
Labels: size/S, pr/no-changelog

#950 add nil check of showonly interface value
  .changelog/950.txt
  helm/data_template.go
  helm/data_template_test.go
Labels: size/XS

#922 ignore dependabot in changelog checker
  .github/workflows/changelog-checker.yml
Labels: size/XS, pr/no-changelog

#963 Update CHANGELOG for v2.7.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#962 Add debug message for cluster unreachable at plan time
  helm/resource_release.go
Labels: size/XS, pr/no-changelog
