Repository hashicorp/terraform-provider-helm, pull requests merged in 2022-06, with the labels that each got.

#869 Add post renderer args
  CHANGELOG.md
  helm/resource_release.go
  helm/resource_release_test.go
  website/docs/r/release.html.markdown
Labels: size/M, documentation

#857 Don't persist diff to the state when an update fails
  helm/resource_release.go
Labels: size/XS

#841 feat(repo): add pass_credentials option
  helm/data_template.go
  helm/resource_release.go
Labels: size/XS

#882 Add go-changelog
  .changelog/changelog.tmpl
  .changelog/note.tmpl
  .github/workflows/changelog-checker.yml
  CHANGELOG_GUIDE.md
  GNUmakefile
Labels: size/L

#890 Update containerd to v1.6.6
  go.mod
  go.sum
  vendor/github.com/containerd/containerd/version/version.go
  vendor/modules.txt
Labels: size/XL, dependencies, pr/no-changelog

#891 Update CHANGELOG.md for v2.6.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#802 Update README.md TF logo location
  README.md
Labels: size/XS

#902 Fix formatting
  helm/provider.go
Labels: size/XS, pr/no-changelog
