Repository hashicorp/terraform-provider-helm, pull requests merged in 2023-03, with the labels that each got.

#1049 Add HashiCorp copyright headers
  .copywrite.hcl
  .github/workflows/hc-copywrite.yml
  .github/workflows/tests.yaml
Labels: size/S, pr/no-changelog

#1085 Fix acceptance tests
  helm/resource_release_test.go
Labels: size/L, pr/no-changelog

#1071 Add `set_list` attribute in helm_release
  .changelog/1071.txt
  helm/data_template.go
  helm/resource_release.go
  helm/resource_release_test.go
  helm/testdata/charts/test-chart-v2/values.yaml
  website/docs/d/template.html.markdown
  website/docs/r/release.html.markdown
Labels: size/L, documentation
