Repository hashicorp/terraform-provider-helm, pull requests merged in 2023-01, with the labels that each got.

#1027 Update `helm_template` documentation
  website/docs/d/template.html.markdown
Labels: pr/no-changelog

#1028 .github/workflows: Switch pr-size-labeler action to upstream
  .github/workflows/pull-request.yml
Labels: pr/no-changelog

#982 Add StateMigrator for pass_credentials and wait_for_jobs
  .changelog/982.txt
  helm/resource_release.go
  helm/resource_release_test.go
  helm/test-chart-1.2.3.tgz
Labels: size/M

#1026 Add GCS/S3 plugin docs
  website/docs/r/release.html.markdown
Labels: size/M, documentation, pr/no-changelog

#1031 🐛 Update GitHub CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: size/XS, pr/no-changelog

#1030 Add OCI repo docs
  website/docs/r/release.html.markdown
Labels: size/XS, documentation, pr/no-changelog

#1012 Configurable burst_limit
  helm/provider.go
  helm/structure_kubeconfig.go
  website/docs/index.html.markdown
Labels: size/XS, documentation, pr/no-changelog
