Repository hashicorp/terraform-provider-helm, pull requests merged in 2023-07, with the labels that each got.

#1180 Update FAQ.md
  _about/FAQ.md
Labels: size/XS, pr/no-changelog

#1185 add Jira Github Actions
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/L, pr/no-changelog

#1190 update Jira GHA | removing components and adding TeamR&D
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/XS, pr/no-changelog

#1192 Jira gha #3
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/XS, pr/no-changelog

#1194 Jira gha #4
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/XS, pr/no-changelog

#1197 Jira gha test
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/XS, pr/no-changelog

#1200 Jira gha issues test
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/XS, pr/no-changelog

#1202 jira-issues GHA
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/XS, pr/no-changelog

#1204 Jira gha - remove `check if team member` and `Education` blocks
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/S, pr/no-changelog

#1206 JIRA GHA: Add labels and `edited` in types
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/M, pr/no-changelog

#1211 fix jira issue type
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/XS

#1213 JIRA GHA Integration
  .github/workflows/jira-issues.yml
  .github/workflows/jira-pr.yml
Labels: size/XS, pr/no-changelog, github_actions
