Repository hashicorp/terraform-provider-helm, pull requests merged in 2023-08, with the labels that each got.

#1228 Add 'name' field validation to be limited to 53 characters
  .changelog/1228.txt
  helm/resource_release.go
  helm/resource_release_test.go
  website/docs/r/release.html.markdown
Labels: size/S, documentation

#1176 resolve version conflicts with local chart
  .changelog/1176.txt
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/M

#1231 add nil check in `set_list.value`
  .changelog/1231.txt
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/S

#1232 v2.11.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog
