Repository hashicorp/terraform-provider-helm, pull requests merged in 2024-10, with the labels that each got.

#1494 Rename resource names
  helm-framework/helm/data_source_helm_template.go
  helm-framework/helm/provider.go
  helm-framework/helm/resource_helm_release.go
Labels: size/S

#1499 v2.16.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#1501 Fix nil pointer deref panic on helm_release destroy
  .changelog/1501.txt
  helm/resource_release.go
Labels: size/XS

#1504 v2.16.1
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#1506 Tidy import function
  helm-framework/helm/resource_helm_release.go
Labels: size/XS

#1507 Remove blocks from helm_release resource schema
  helm-framework/helm/data_source_helm_template.go
  helm-framework/helm/resource_helm_release.go
Labels: size/L

#1508 Add godoc comments to structs
  helm-framework/helm/provider.go
Labels: size/XS

#1509 Including mutex as part of meta
  helm-framework/helm/data_source_helm_template.go
  helm-framework/helm/provider.go
  helm-framework/helm/resource_helm_release.go
Labels: size/S

#1515 add first_deployed and last_deployed timestamp fields to Helm release…
  helm-framework/helm/resource_helm_release.go
Labels: size/S

#1516 `helm-framework`: refactor `metadata` from `ListNestedAttribute` -> `SingleNestedAttribute`
  helm-framework/helm/resource_helm_release.go
  helm-framework/helm/resource_helm_release_test.go
Labels: size/L

#1514 `helm-framework`: ModifyPlan refactor 2
  helm-framework/helm/resource_helm_release.go
Labels: size/XS

#1512 Fix failing template tests
  helm-framework/helm/data_template_test.go
  scripts/get-version-matrix.sh
Labels: size/XS

#1513 Removing fmt.Println
  helm-framework/helm/kubeConfig.go
Labels: size/XS
