Repository hashicorp/terraform-provider-helm, pull requests merged in 2024-06, with the labels that each got.

#1377 Add support for deferred actions
  .changelog/1377.txt
  .github/workflows/acceptance_test_dfa.yaml
  go.mod
  go.sum
  helm/provider.go
  helm/test-infra/gke/main.tf
  helm/testing/config-da-basic/test.tf
  helm/testing/deferred_actions_test.go
Labels: size/XL

#1380 Add new fields to release metadata, fix issue with test suite
  .changelog/1380.txt
  docs/resources/release.md
  go.mod
  helm/provider_test.go
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/S

#1387 Simplify past tags detection in release workflow
  .github/workflows/release.yaml
Labels: size/XS, pr/no-changelog

#1393 add `oncall_review_assigner` step into `issue-opened.yml` workflow
  .github/workflows/issue-opened.yml
Labels: size/S, pr/no-changelog
