Repository hashicorp/terraform-provider-helm, pull requests merged in 2024-08, with the labels that each got.

#1454 Clean up changelog
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#1453 🎉 v2.14.1
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#1451 Fix description for `set_list` parameters
  docs/data-sources/template.md
  docs/resources/release.md
  helm/data_template.go
  helm/resource_release.go
Labels: size/XS, pr/no-changelog, no-documentation

#1455 PSS-277: Bump hashicorp/ghaction-terraform-provider-release/.github/workflows/hashicorp.yml to v4.0.1
  .github/workflows/release.yaml
Labels: size/XS, pr/no-changelog

#1450 fix: quoting error in check-docs workflow
  .github/workflows/documentation-check.yaml
Labels: size/XS, pr/no-changelog

#1457 Updating get-version-matrix.sh to use $GITHUB_OUTPUT instead of set-output
  scripts/get-version-matrix.sh
Labels: size/XS, pr/no-changelog

#1247 Enable "helm upgrade --install" equivalent behavior
  .changelog/1247.txt
  docs/resources/release.md
  helm/provider.go
  helm/resource_release.go
  helm/resource_release_test.go
  helm/test-chart-1.2.3.tgz
  templates/resources/release.md.tmpl
Labels: size/XL, no-documentation

#1461 Generate changelog for v2.15.0
  CHANGELOG.md
Labels: pr/no-changelog

#1465 Release tidy
  helm-framework/helm/resource_helm_release.go
Labels: size/M

#1466 [Plugin framework migration] Fix: use correct split delimiter on KUBE_CONFIG_PATHS value
  helm-framework/helm/provider.go
Labels: size/XS

#1467 [Helm framework migration] Some tidying up
  helm-framework/helm/resource_helm_release.go
Labels: size/S

#1468 Fix acronyms in struct field names in kubeConfig.go and provider.go
  helm-framework/helm/kubeConfig.go
  helm-framework/helm/provider.go
Labels: size/S

#1469 Creating bool debug
  helm-framework/helm/kubeConfig.go
  helm-framework/helm/provider.go
Labels: size/XS

#1470 Rename registry to registries
  helm-framework/helm/provider.go
Labels: size/XS

#1471 Refactor `ModifyPlan` function in `helm_release.go` (1/2)
  helm-framework/helm/resource_helm_release.go
Labels: size/M, plugin-framework
