Repository hashicorp/terraform-provider-helm, pull requests merged in 2024-09, with the labels that each got.

#1473 refactor: alphabetize schema attributes in HelmReleaseResource
  helm-framework/helm/resource_helm_release.go
Labels: size/S, plugin-framework

#1476 Rename resolveChartName to buildChartNameWithRepository for clarity
  helm-framework/helm/resource_helm_release.go
Labels: size/XS, plugin-framework

#1480 Refactor: Rename SetListList to SetListSlice
  helm-framework/helm/data_source_helm_template.go
  helm-framework/helm/resource_helm_release.go
Labels: size/XS, plugin-framework

#1482 Sort defaultAttributes map and improve schema default handling
  helm-framework/helm/resource_helm_release.go
Labels: size/M

#1491 `CI`: Update `tests.yaml` to include helm-framework branch
  .github/workflows/tests.yaml
Labels: size/XS, pr/no-changelog

#1490 `framework-migration`: m.lock removal and more
  helm-framework/helm/provider.go
  helm-framework/helm/provider_test.go
  helm-framework/helm/resource_helm_release.go
  helm-framework/helm/resource_helm_release_test.go
Labels: size/M

#1458 Fix: only recompute metadata when the version in the metadata changes
  .changelog/1458.txt
  helm/resource_release.go
  helm/resource_release_test.go
Labels: size/S

#1487 Ignore "release: not found" error on helm_resource destroy
  .changelog/1487.txt
  helm/resource_release.go
Labels: size/XS
