Repository hashicorp/terraform-provider-helm, pull requests merged in 2024-07, with the labels that each got.

#1415 `CI`: add 1.5, 1.7, 1.9 terraform versions into get-version-matrix
  scripts/get-version-matrix.sh
Labels: size/XS, pr/no-changelog, CI

#1403 Add issue assigner
  .github/workflows/issue-opened.yml
Labels: size/XS, pr/no-changelog

#1430 CI: set `TF_ACC_TERRAFORM_VERSION` in workflow instead of repo variable
  .github/workflows/acceptance_test_dfa.yaml
Labels: size/XS, pr/no-changelog, CI

#1439 Update documentation section of contribution guide
  _about/PULL_REQUESTS.md
Labels: size/XS, pr/no-changelog

#1440 Add tfplugindocs workflow file
  .github/workflows/documentation-check.yaml
Labels: size/S, pr/no-changelog
