Repository hashicorp/terraform-provider-helm, pull requests merged in 2025-02, with the labels that each got.

#1572 `set.value`: `required` -> `optional`
  .changelog/1572.txt
  docs/data-sources/template.md
  docs/resources/release.md
  helm/data_helm_template.go
  helm/data_helm_template_test.go
  helm/resource_helm_release.go
  helm/resource_helm_release_test.go
Labels: size/M

#1593 Fix docs for exec object in provider config
  docs/index.md
Labels: size/XS, pr/no-changelog

#1592 Add write-only attribute "set_wo"
  .changelog/1592.txt
  docs/resources/release.md
  go.mod
  go.sum
  helm/resource_helm_release.go
  helm/resource_helm_release_test.go
  scripts/get-version-matrix.sh
Labels: size/XL

#1594 v3.0.0-pre2
  CHANGELOG.md
Labels: size/XS, pr/no-changelog
