Repository hashicorp/terraform-provider-helm, pull requests merged in 2025-06, with the labels that each got.

#1633 Implement state upgrader support for helm_release resource
  .changelog/1633.txt
  helm/resource_helm_release.go
  helm/resource_helm_release_stateupgrader.go
  helm/resource_helm_release_stateupgrader_test.go
Labels: size/XL

#1634 Update security scanner configuration
  .release/security-scan.hcl
Labels: size/XS, pr/no-changelog

#1636 v3.0.0
  version/VERSION
Labels: pr/no-changelog

#1639 v3.0.1
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog

#1644 Fix sensitive values being replaced with '(sensitive value)' in Helm deployments
  .changelog/1644.txt
  helm/data_helm_template_test.go
  helm/resource_helm_release.go
  helm/resource_helm_release_test.go
  helm/testdata/charts/test-chart/templates/secrets.yaml
  helm/testdata/charts/test-chart/values.yaml
Labels: size/M

#1651 Fix invalid syntax for nested kubernetes config in provider example documentation
  docs/index.md
Labels: size/XS, pr/no-changelog

#1649 helm_release: Fix postrender running when binaryPath is set to nil
  .changelog/1649.txt
  helm/resource_helm_release.go
Labels: size/M

#1656 Fix devel planmodifier
  .changelog/1656.txt
  helm/resource_helm_release.go
Labels: size/XS

#1655 Restore support for KUBE_PROXY_URL environment variable
  .changelog/1655.txt
  helm/provider.go
Labels: size/XS

#1648 helm_release: Make description attribute Computed
  .changelog/1648.txt
  helm/resource_helm_release.go
Labels: size/XS

#1658 v3.0.2
  CHANGELOG.md
Labels: size/XS, pr/no-changelog
