Repository hashicorp/terraform-provider-helm, pull requests merged in 2025-07, with the labels that each got.

#1674 Bump dependencies
  go.mod
  go.sum
  helm/manifest_json_test.go
  helm/resource_helm_release_test.go
Labels: size/XL, pr/no-changelog

#1668 Add qps support
  .changelog/1668.txt
  docs/index.md
  helm/kubeconfig.go
  helm/provider.go
Labels: size/S

#1676 Fix duplicate `set` attribute in `helm_release` docs
  docs/resources/release.md
Labels: size/XS, pr/no-changelog

#1675 Add upgrade_install support
  .changelog/1675.txt
  helm/resource_helm_release.go
  helm/resource_helm_release_stateupgrader.go
  helm/resource_helm_release_test.go
Labels: size/XL

#1680 Add take_ownership field
  .changelog/1680.txt
  docs/resources/release.md
  helm/resource_helm_release.go
  helm/resource_helm_release_stateupgrader.go
  helm/resource_helm_release_test.go
Labels: size/M
