Repository hashicorp/terraform-provider-helm, pull requests merged in 2025-03, with the labels that each got.

#1607 fix(examples): update outdated examples to reflect current usage
  examples/data-sources/template/example_1.tf
  examples/data-sources/template/example_2.tf
  examples/example_1.tf
  examples/example_2.tf
  examples/example_3.tf
  examples/example_4.tf
  examples/example_5.tf
  examples/example_6.tf
  examples/resources/release/example_1.tf
  examples/resources/release/example_11.tf
  examples/resources/release/example_4.tf
  examples/resources/release/example_8.tf
  examples/resources/release/example_9.tf
Labels: size/L

#1604 Update outdated README
  README.md
Labels: size/XS, pr/no-changelog

#1608 Update helm dependency to v3.17.2
  .changelog/1608.txt
  go.mod
  go.sum
Labels: size/XL
